# Load configuration modules
source-file ~/.config/tmux/settings.conf
source-file ~/.config/tmux/keybindings.conf
source-file ~/.config/tmux/plugins.conf
source-file ~/.config/tmux/appearance.conf

run '~/.tmux/plugins/tpm/tpm'

bind-key -T copy-mode-vi y send-keys -X copy-pipe "pbcopy" \; display-message "Yanked!"

